all:
	g++ -std=c++11 uniform-initialization.cpp -o bin/uniform-initialization

clang:
	clang++ -std=c++11 uniform-initialization.cpp -o bin/uniform-initialization

run:
	./bin/random

clean:
	rm bin/*
